### ISSUE TITLE
Failed to load a language-git package grammar

### ISSUE THREAD

**Issue by FirixQ** [atom/language-git#43] opened 2017-05-22 20:58 UTC
Steps to reproduce:

1. Start atom

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-git](https://github.com/atom/language-git) package 0.19.0

### Stack Trace

Failed to load a language-git package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Matt\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git config.json' in C:\Users\Matt\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git config.json

Error: ENOENT: no such file or directory, open 'C:\Users\Matt\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git config.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/language-git/grammars/git config.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
script 3.15.0 
```

**Comment by 50Wliu** [comment] 2017-05-23 17:53
Closing as a duplicate of atom/language-java#94.  Reinstalling should fix the issue.

**Closed by 50Wliu** 2017-05-23 17:53 UTC
