### ISSUE TITLE
Failed to load a language-git package grammar

### ISSUE THREAD

**Issue by justOlzhas** [atom/language-git#61] opened 2017-08-04 08:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-git](https://github.com/atom/language-git) package 0.19.1

### Stack Trace

Failed to load a language-git package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Relog Mobile\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git config.json' in C:\Users\Relog Mobile\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git config.json

Error: ENOENT: no such file or directory, open 'C:\Users\Relog Mobile\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git config.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-git/grammars/git config.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-babel 2.68.0 
language-ocaml 1.9.5 
linter 2.2.0 
linter-eslint 8.2.1 
minimap 4.29.3 
nuclide 0.243.0 
platformio-ide-terminal 2.5.4 
react-native-snippets 0.3.0 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by 50Wliu** [comment] 2017-08-04 14:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-java#94. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-08-04 14:54 UTC
