### ISSUE TITLE
Failed to load a language-git package grammar

### ISSUE THREAD

**Issue by Jazzii01** [atom/language-git#44] opened 2017-05-24 13:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-git](https://github.com/atom/language-git) package 0.19.0

### Stack Trace

Failed to load a language-git package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Jazzii\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git rebase message.json' in C:\Users\Jazzii\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git rebase message.json

Error: ENOENT: no such file or directory, open 'C:\Users\Jazzii\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git rebase message.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/language-git/grammars/git rebase message.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.7 
atom-material-syntax 1.0.6 
scroll-through-time 0.2.0 
toggler 0.3.0 
```

**Comment by 50Wliu** [comment] 2017-05-24 14:30
Closing as a duplicate of atom/language-java#94.

**Closed by 50Wliu** 2017-05-24 14:30 UTC
