### ISSUE TITLE
Failed to load a language-git package grammar

### ISSUE THREAD

**Issue by adam6650261** [atom/language-git#57] opened 2017-07-25 23:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-git](https://github.com/atom/language-git) package 0.19.1

### Stack Trace

Failed to load a language-git package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git rebase message.json' in C:\Users\Administrator\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git rebase message.json

Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git rebase message.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-git/grammars/git rebase message.json:1:1
```

### Commands

```
     -1:13.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -0:20.8.0 core:copy (atom-pane.pane)
```

### Non-Core Packages

```
autocomplete-json 5.5.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
color-picker 2.2.5 
docblockr 0.10.5 
emmet 2.4.3 
file-icons 2.1.8 
highlight-selected 0.11.2 
linter 1.11.18 
linter-flake8 1.13.4 
minimap 4.25.7 
px2rem-plus 0.3.1 
python-debugger 0.2.0 
python-indent 1.0.3 
python-tools 0.6.9 
regex-railroad-diagram 0.16.0 
Remote-FTP 1.1.0 
script 3.15.0 
simplified-chinese-menu 5.3.4 
tool-bar 1.1.0 
```

**Comment by 50Wliu** [comment] 2017-07-26 00:27
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-java#94. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-07-26 00:27 UTC
