### ISSUE TITLE
Unwanted title length warning highlighting in message

### ISSUE THREAD

**Issue by lucascosti** [atom/language-git#28] opened 2016-11-14 01:33 UTC
Cloned as requested by @50Wliu  from https://github.com/atom/language-git/issues/26, as it doesn't seem to be fixed:

![screenshot from 2016-11-14 11-30-51](https://cloud.githubusercontent.com/assets/4434330/20250775/18421e14-aa5e-11e6-86f0-943baaec16b1.png)

Atom 1.12.2 running on Fedora 24.
language-git 0.15.0

**Comment by hasit** [comment] 2016-11-14 05:23
The length warning should only be showing for the first line, right?

**Comment by lucascosti** [comment] 2016-11-14 05:44
@hasit correct. The length checking should apply to only the first line.

**Comment by hasit** [comment] 2016-11-15 01:07
I think I know what is going wrong. To see for yourself, open atom and try writing a commit message. Also, open 'Developer Tools'. `alt+cmd+I` for Mac.

Atom recognizes
'message' with `class=meta scope message git-commit` and
'metadata' with `class=meta scope metadata git-commit`.

There is no distinction between subject line and body lines in the message section. We will have to update the grammar to exclude `data-screen-row` tags with values after 0.

**Comment by walles** [comment] 2016-11-18 12:15
I don't think this is a bug:
http://chris.beams.io/posts/git-commit/#wrap-72

#29 should make this more obvious.

**Comment by hasit** [comment] 2016-11-19 03:35
Well, is it possible to wrap just the body at 72 characters?

**Comment by thomasjo** [comment] 2016-11-21 14:08
As mentioned by @walles, lines in the body should be wrapped at column 72. From the screenshot it is obvious that lines are soft-wrapped, but they need to be explicitly wrapped.

This is working as intended, and I'm closing this as `wontfix`.

**Closed by thomasjo** 2016-11-21 14:08 UTC
Labels: bug

**Comment by lucascosti** [comment] 2016-11-21 23:27
IMO, a paragraph of text (unlike the title, or code) shouldn't have restrictions on length, or have hard breaks inserted for wrapping. Although git itself doesn't wrap the lines automatically, any software displaying it does (e.g. a terminal emulator, git application, text editor, word processor, etc). 

I disagree with decision, but if that is the consensus, then so be it.
